name: driver
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # A powerful Http client for Dart, which supports Interceptors,
  # Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^4.0.6
  # GetX is an extra-light and powerful solution for Flutter.
  # It combines high-performance state management, intelligent dependency injection,
  # and route management quickly and practically.
  get: ^4.6.5
  localstorage: ^4.0.0+1
  flutter_native_splash: ^2.2.17
  google_fonts: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#1D273A"
  image: "assets/logo.png"
  android_12:
    image: "assets/logo.png"
    color: "#1D273A"
    color_dark: "#1D273A"
